accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.indexView, name='index'),
    path('signup/', views.SignupView, name="signup"),
    path('login/', views.LoginPage, name="login"),
    path('logout/', views.Logout, name="logout"),



    # path('viloyat/', views.ViloyatView, name='viloyat'),

]

base_app/urls.py
from django.urls import path
from . import views

app_name = 'base_app'

urlpatterns = [


    path('tinglovchi/', views.TinglovchiView, name='tinglovchi'),
    # path('tinglovchi/', views.TinglovchiView.as_view(), name='tinglovchi'),

    path('davomat/', views.DavomatView, name='davomat'),
    path('attandance/', views.attandance, name='attandance'),
    path('viloyat/', views.ViloyatView, name='viloyat'),
    path('toifa/', views.ToifaView, name='toifa'),
    path('dars/', views.DarsView, name='dars'),
    path('monitoring/', views.MonitoringView.as_view(), name="monitoring"),
    path('malaka/', views.MalakaView.as_view(), name="malaka"),
    path('bitiruv/', views.BitiruvView, name="bitiruv"),
    path('simple_upload/', views.simple_upload, name='simple_upload'),
    path('yakun/', views.export_yakun, name='yakun'),
    
    path('export/xlsx/$', views.export_users_xls, name='export_users_xlsx'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('base_app/', include('base_app.urls', namespace='base_app')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base_app/models.py
from enum import unique
from django.db import models
from django.db.models.base import Model
from django.db.models.deletion import CASCADE
from accounts.models import MyUser
import datetime


class MO_yili(models.Model):
    yil = models.DateField()

    def __str__(self):
        return str(self.yil)


class MO_oyi(models.Model):
    oy = models.CharField(max_length=250, verbose_name='MO oyi')

    def __str__(self):
        return self.oy


class Viloyat(models.Model):
    name = models.CharField(
        max_length=250, verbose_name="Viloyat nomi", unique=True)

    def __str__(self):
        return self.name


class Tuman(models.Model):
    viloyat_id = models.ForeignKey(Viloyat, on_delete=models.CASCADE)
    name = models.CharField(
        max_length=250, verbose_name="Tuman (shahar)", unique=True)

    def __str__(self):
        return self.name


class Toifa(models.Model):
    toifa = models.CharField(max_length=250, verbose_name="Toifa", unique=True)

    def __str__(self):
        return str(self.toifa)


class Ilmiy_daraja(models.Model):
    daraja = models.CharField(max_length=250, null=True, blank=True)

    def __str__(self):
        return str(self.id)


class Shakl(models.Model):
    shakl = models.CharField(max_length=15)

    def __str__(self):
        return self.shakl


class Guruh(models.Model):
    toifa = models.ForeignKey(
        Toifa, on_delete=models.SET_NULL, null=True, blank=True)
    guruh = models.CharField(max_length=250, null=True,
                             blank=True, unique=True)

    def __str__(self):
        return str(self.guruh)


class Modul(models.Model):
    modul = models.CharField(max_length=250)

    def __str__(self):
        return self.modul


class Tinglovchi(models.Model):
    fish = models.CharField(max_length=250)
    yil = models.DateField(verbose_name="MO oyi", auto_now_add=True)
    oy = models.DateField(verbose_name="MO oyi", auto_now_add=True)
    # shakl = models.ForeignKey(Shakl, on_delete=models.CASCADE)
    viloyat = models.ForeignKey(
        Viloyat, on_delete=models.CASCADE, verbose_name="Viloyat")
    # tuman = models.ForeignKey(Tuman, on_delete=models.CASCADE, verbose_name="Tuman(shahar)")
    joy = models.CharField(
        max_length=250, verbose_name="Ta'lim muassasasi nomi")
    tell = models.CharField(max_length=15, verbose_name="Telefon nomer")
    email = models.EmailField(verbose_name="Email", null=True, blank=True)
    toifa = models.ForeignKey(
        Toifa, on_delete=models.CASCADE, verbose_name="Toifa")
    guruh = models.ForeignKey(
        Guruh, on_delete=models.CASCADE, null=True, blank=True)
    # daraja = models.ForeignKey(Ilmiy_daraja, on_delete=models.CASCADE)
    # himoya_yil = models.DateField(null=True, blank=True)

    def __str__(self):
        if self.fish:
            return f'{self.fish}'
        return f'{self.id}'


class Monitoring(models.Model):
    tinglovchi = models.ForeignKey(Tinglovchi, on_delete=models.CASCADE)
    kirish_test = models.CharField(max_length=3, null=True, blank=True)
    chiqish_test = models.CharField(max_length=3, null=True, blank=True)
    kirish_sana = models.DateField(null=True, blank=True)
    chiqish_sana = models.DateField(null=True, blank=True)

    def __str__(self):
        return str(self.tinglovchi)


class Dars(models.Model):
    active = [
        ('passiv', "Passiv"),
        ('yaxshi', 'Yaxshi'),
        ('faol', 'Faol')
    ]
    oqituvchi = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    tinglovchi = models.ForeignKey(Tinglovchi, on_delete=models.CASCADE)
    mavzu = models.CharField(max_length=250)
    modul = models.ForeignKey(Modul, on_delete=models.CASCADE)
    sana = models.DateField(default=datetime.datetime.today())
    toifa = models.ForeignKey(Toifa, on_delete=models.CASCADE)
    guruh = models.ForeignKey(
        Guruh, on_delete=models.CASCADE, null=True, blank=True)
    soat = models.PositiveIntegerField()
    is_absent = models.CharField(default="+", max_length=10)
    is_active = models.CharField(max_length=50, choices=active)

    def __str__(self):
        return str(self.tinglovchi)


class Bitiruv(models.Model):
    toifa = models.ForeignKey(Toifa, on_delete=models.CASCADE)
    guruh = models.ForeignKey(
        Guruh, on_delete=models.CASCADE, null=True, blank=True, default=None)
    tinglovchi = models.ForeignKey(Tinglovchi, on_delete=models.CASCADE)
    bmi_mavzu = models.CharField(max_length=250)
    bmi_rahbar = models.CharField(max_length=250)
    bmi_ball = models.PositiveIntegerField()
    file = models.FileField(upload_to='bitiruv/')
    monitoring = models.ForeignKey(
        Monitoring, on_delete=models.CASCADE, null=True, blank=True)
    sana = models.DateField(auto_now_add=True)

    # class Meta:
    #     unique_together = ('tinglovchi',)

base_app/views.py
import datetime
from django.forms.forms import Form
import pytz
import json
import re
import urllib
import xlwt

from tablib import Dataset
from django.contrib.auth.mixins import LoginRequiredMixin

from django.http.response import HttpResponse

from .resources import TinglovchiResource
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views.generic import TemplateView, CreateView, ListView
from . import models
from .forms import TinglovchiForm, BitiruvForm

from django.contrib.auth.decorators import login_required, user_passes_test

from accounts.models import Kim, MyUser
from import_export.admin import ImportExportModelAdmin
from django.db.models import Count
from base_app import resources
from django.utils.timezone import utc
from django.db.models import Q


class MonitoringView(LoginRequiredMixin, ListView):
    template_name = 'monitoring.html'
    model = models.Toifa

    def post(self, request):
        if request.is_ajax() and request.method == "POST":
            if request.POST.get('select') == 'toifa':
                toifa = request.POST['toifa']
                try:
                    guruh = list(models.Toifa.objects.get(
                        toifa=toifa).guruh_set.all().values())
                except:
                    pass
                return JsonResponse({'guruh': guruh})
            elif request.POST.get('select') == 'search':
                toifa = request.POST['toifa']
                guruh = request.POST['guruh']
                try:
                    guruh = models.Guruh.objects.get(guruh=guruh)
                except:
                    pass
                if toifa == 'Guruh rahbari':

                    start_date = datetime.datetime.now().date()
                    end_date = start_date + datetime.timedelta(days=45)

                    tinglovchi1 = guruh.tinglovchi_set.filter(
                        oy__lte=end_date).values()
                    tinglovchi2 = guruh.tinglovchi_set.filter(
                        oy__gte=start_date).values()
                    tinglovchi = list(tinglovchi1.union(tinglovchi2))

                    return JsonResponse({"ting": tinglovchi})
                else:
                    tinglovchi = list(models.Toifa.objects.get(toifa=toifa).tinglovchi_set.filter(
                        oy__month=datetime.datetime.now().month,
                        yil__year=datetime.datetime.now().year).values())
                    return JsonResponse({"ting": tinglovchi})

            elif request.POST.get('select') == 'test':
                kirish_test = request.POST.getlist('kirish[]')
                chiqish_test = request.POST.getlist('chiqish[]')
                ting_id = request.POST.getlist('id_ting[]')
                guruh = request.POST.get('guruh')

                for i in ting_id:
                    m = models.Monitoring()
                    ind = ting_id.index(i)
                    m.tinglovchi = models.Tinglovchi.objects.get(id=i)
                    m.kirish_test = kirish_test[ind]
                    m.chiqish_test = chiqish_test[ind]
            

                    m.save()

                return JsonResponse({'statuc': 'ok'})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['admin'] = MyUser.objects.filter(username=self.request.user)
        return context


class MalakaView(LoginRequiredMixin, ListView):
    template_name = 'malaka.html'
    model = models.Tinglovchi

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['toifalar'] = models.Toifa.objects.all()
        context['ting'] = models.Tinglovchi.objects.filter(oy__month=datetime.datetime.now().month,
                                                           yil__year=datetime.datetime.now().year)

        context['soni'] = models.Tinglovchi.objects.values(
            'toifa').annotate(soni=Count('toifa'))
        context['ting'] = models.Tinglovchi.objects.filter(oy__month=datetime.datetime.now().month,
                                                           yil__year=datetime.datetime.now().year)

        return context


@login_required()
def BitiruvView(request):
    form = BitiruvForm()
    if request.method == 'POST' and request.is_ajax():
        if request.POST.get('select') == 'toifa':
            toifa = request.POST.get('toifa')

            if toifa == 'Guruh rahbari':
                guruh = list(models.Toifa.objects.get(
                    toifa=toifa).guruh_set.all().values())
                return JsonResponse({'guruh': guruh})
            else:
                ting = list(
                    models.Toifa.objects.get(toifa=toifa).tinglovchi_set.filter(oy__month=datetime.datetime.now().month,
                                                                                yil__year=datetime.datetime.now().year).values())
                return JsonResponse({'ting': ting})
        elif request.POST.get('select') == 'guruh':
            guruh = request.POST.get('guruh')
            guruh = models.Guruh.objects.get(guruh=guruh)
            start_date = datetime.datetime.now().date()
            end_date = start_date + datetime.timedelta(days=45)

            tinglovchi1 = guruh.tinglovchi_set.filter(
                oy__lte=end_date).values()
            tinglovchi2 = guruh.tinglovchi_set.filter(
                oy__gte=start_date).values()
            ting = list(tinglovchi1.union(tinglovchi2))

            return JsonResponse({'ting': ting})

        elif request.POST.get('select') == 'data':
            toifa = request.POST.get('toifa')
            guruh = request.POST.get('guruh')
            tinglovchi = request.POST.get('tinglovchi')
            mavzu = request.POST.get('mavzu')
            rahbar = request.POST.get('rahbar')
            ball = request.POST.get('ball')
            file = request.POST.get('file')

            b = models.Bitiruv()

            b.toifa = models.Toifa.objects.get(id=toifa)

            try:
                b.guruh = models.Guruh.objects.get(id=guruh)
            except:
                b.guruh = None

            b.tinglovchi = models.Tinglovchi.objects.get(id=tinglovchi)

            b.bmi_mavzu = mavzu
            b.bmi_rahbar = rahbar
            b.bmi_ball = ball
            b.file = file
            try:
                b.monitoring = models.Monitoring.objects.get(
                    tinglovchi_id=tinglovchi)
            except:
                return JsonResponse({'status': 'xato'})


         


            b.save()
            return JsonResponse({'status': 'ok'})
    context = {
        'form': form,
    }
    return render(request, 'bitiruv.html', context)


# def is_dekan(user):
#     try:
#         k = Kim.objects.get(kim='dekanat')
#         return user.is_authenticated and user.kim.kim == 'dekanat'
#     except:
#         return False
# @user_passes_test(is_dekan)
@login_required()
def TinglovchiView(request):
    form = TinglovchiForm()
    if request.method == 'POST':
        form = TinglovchiForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('ism')
            messages.success(request, 'ok')
            return redirect('base_app:tinglovchi')
        else:
            pass

    data = {
        'form': form,
    }
    return render(request, 'ting.html', context=data)


def ViloyatView(request):
    if request.method == 'POST':
        viloyat = request.POST["vil"]
        tuman = list(models.Viloyat.objects.get(
            id=viloyat).tuman_set.all().values())
        return JsonResponse({'t': tuman})


def ToifaView(request):
    if request.method == 'POST':
        toifa = request.POST["toifa"]
        guruh = list(models.Toifa.objects.get(
            id=toifa).guruh_set.all().values())
        return JsonResponse({'guruh': guruh})


# def is_teacher(user):
#     try:
#         k = Kim.objects.get(kim='O\'qituvchi')
#         return user.is_authenticated and user.kim.kim == 'O\'qituvchi'
#     except:
#         return False
#
#
# @user_passes_test(is_teacher)

@login_required()
def DavomatView(request):
    oqituvchi = models.MyUser.objects.all()
    toifa = models.Toifa.objects.all()
    guruh = models.Guruh.objects.all()
    modul = models.Modul.objects.all()
    admin = MyUser.objects.filter(username=request.user)
    if request.method == 'POST':
        if request.POST.get('select') == 'toifa':
            try:
                toifa = models.Toifa.objects.get(id=request.POST.get('id'))
            except:
                return JsonResponse({'gs': [], })

            guruhs = list(toifa.guruh_set.all().values())
            return JsonResponse({'gs': guruhs})
        elif request.POST.get('select') == 'guruh':
            try:
                guruh = models.Guruh.objects.get(id=request.POST.get('guruh'))

            except:
                toifa = models.Toifa.objects.get(id=request.POST.get('toifa'))
                students = list(toifa.tinglovchi_set.filter(oy__month=datetime.datetime.now().month,
                                                            yil__year=datetime.datetime.now().year).values())
                return JsonResponse({'s': students})
            start_date = datetime.datetime.now().date()
            end_date = start_date + datetime.timedelta(days=45)

            students1 = guruh.tinglovchi_set.filter(oy__lte=end_date).values()
            students2 = guruh.tinglovchi_set.filter(
                oy__gte=start_date).values()
            students = list(students1.union(students2))

            return JsonResponse({'s': students})

    context = {
        "oqituvchi": oqituvchi,
        "toifa": toifa,
        "guruh": guruh,
        "modul": modul,
        "admin": admin
    }
    return render(request, 'davomat.html', context)


def attandance(request):

templates/bitiruv.html
{% extends 'index.html' %}
{% load static %}
{% block content %}

<div class="mainbox">
    <div class="container">
        <div class="sectionHeader">
            <div class="textbox">
                <div class="tbox">
                    <h1>Bitiruv malakaviy ishi</h1>
                </div>
            </div>
            <div class="name_box1">
                <p>{{ request.user }}</p>
                <!-- <img src="{% static 'img/Rahbar_maqolasi.jpg' %}" alt=""> -->
            </div>
        </div>
        <div class="row">
            <div class="name">
                <div class="name_box">
                    <form action="#">
                        {% csrf_token %}
                        <input id="csrf_token" value="{{csrf_token}}" disabled hidden>
                        <div class="col_box">
                            <p class="ism">Malaka oshirish toifasi</p>
                            {{ form.toifa }}
                        </div>
                        <div class="col_box">
                            <p class="ism">Guruh raqami</p>
                            {{ form.guruh }}
                        </div>
                        <div class="col_box">
                            <p class="ism">Tinglovchining I.F.O.</p>
                            {{ form.tinglovchi }}
                        </div>
                        <div class="col_box">
                            <p class="ism">BMI mavzusi</p>
                            {{ form.bmi_mavzu }}
                        </div>
                        <div class="col_box">
                            <p class="ism">BMI rahbari I.F.O.</p>
                            {{ form.bmi_rahbar }}
                        </div>
                        <div class="col_box">
                            <p class="ism">BMI bali </p>
                            {{ form.bmi_ball }}
                        </div>
                        <div class="col_box">
                            <p class="ism">BMI ni yuklash</p>
                            <!-- <a href="#">Faylni tanlash</a> -->
                            {{ form.file }}
                            <span class="span">.pdf(10 mb)</span>
                        </div>
                    </form>
                </div>
                <div class="sert">
                    <img src="{% static 'img/sertfikat.png' %}" alt="">
                </div>
            </div>
            <div class="button">
                <button class="btn" id="bekor">Bekor qilish</button>
                <button class="btn1" id="save_btn">Saqlash</button>
            </div>
        </div>
    </div>
</div>
</section>

<script src="{% static 'js/jQuery.min.js' %}"></script>
<script src="{% static 'slick/slick.js ' %}" type="text/javascript " charset="utf-8 "></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/main1.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-sweetalert/1.0.1/sweetalert.min.css">
<script>
    $(document).ready(function (e) {
        $("#bekor").click(function () {
            swal("nimadir")
        })

        document.getElementById("id_toifa").addEventListener('change', e => {
            var toifa = $('#id_toifa').find(":selected").text();
            console.log(toifa);
            $.ajax({
                url: '/base_app/bitiruv/',
                type: 'POST',
                data: {
                    select: 'toifa',
                    'toifa': toifa,
                    csrfmiddlewaretoken: $('#csrf_token').val(),
                },
                'Content-type': 'application/json',
                success: function (res) {

                    $('#id_guruh').empty();
                    $("#id_guruh").append('<option></option>');
                    $.each(res['guruh'], function (i, v) {
                        $('#id_guruh').append('<option value="' + v['id'] + '">' + v["guruh"] + '</option>')
                    });
                    $('#id_tinglovchi').empty();
                    $('#id_tinglovchi').append('<option></option>');
                    $.each(res['ting'], function (i, v) {
                        $("#id_tinglovchi").append('<option value="' + v['id'] + '" >' + v['fish'] + '</option>');
                    })

                },
                error: function (err) {
                    console.log(err);
                }
            })
        })
    })

    document.getElementById('id_guruh').addEventListener('change', e => {
        var guruh = $('#id_guruh').find(":selected").text();
        console.log(guruh);
        $.ajax({
            url: '/base_app/bitiruv/',
            type: 'POST',
            data: {
                select: 'guruh',
                'guruh': guruh,
                csrfmiddlewaretoken: $("#csrf_token").val(),
            },
            'Content-type': 'application/json',
            success: function (res) {
                $("#id_tinglovchi").empty();
                $('#id_tinglovchi').append('<option></option>');
                $.each(res['ting'], function (i, v) {
                    $("#id_tinglovchi").append('<option value="' + v['id'] + '" >' + v['fish'] + '</option>');
                })
            },
            error: function (err) {
                console.log(err);
            }
        })
    })

    document.getElementById('save_btn').addEventListener('click', e => {
        var toifa = $('#id_toifa').find(':selected').val();
        var guruh = $('#id_guruh').find(':selected').val();
        var tinglovchi = $('#id_tinglovchi').find(':selected').val();
        var mavzu = $('#id_bmi_mavzu').val();
        var rahbar = $('#id_bmi_rahbar').val();
        var ball = $('#id_bmi_ball').val();
        var file = $('#id_file').val();

        $.ajax({
            url: '/base_app/bitiruv/',
            type: 'POST',
            data: {
                select: 'data',
                'toifa': toifa,
                'guruh': guruh,
                'tinglovchi': tinglovchi,
                'mavzu': mavzu,
                'rahbar': rahbar,
                'ball': ball,
                'file': file,
                csrfmiddlewaretoken: $("#csrf_token").val(),
            },
            'Content-type': 'application/json',
            success: function (res) {
                console.log(res);
                if (res['status'] == 'ok') {

                    swal("Ma'lumotlar saqlandi!", "saqlandi", "success");
                }
                else if (res['status'] == 'xato') {
                    console.log(res);
                    // alert('Avval Ushbu tinglovchining chiqish testi bali kiritilgan bo\'lishi kerak ');
                    swal("Xatolik!", "Avval Ushbu tinglovchining chiqish testi bali kiritilgan bo\'lishi kerak !", "error");
                } else if (res['status'] == 'bor') {
                    swal("Xatolik!", "Ushbu tinglovchining malumotlari saqlangan!", "info");
                }

            },
            error: function (err) {
                console.log(err);
            }


        })

    })







    // function refresh(){
    //       window.location.reload("Refresh")
    //     }



    function displayVals() {
        var i = 1;
        var vals = [];
        var noVal = "undefined";
        $('input[type="time"]').each(function () {
            var x = $(this).val().split(':');
            var h = x[0];
            var m = x[1];
            if (h < 10) {
                h = h.substring(1);
            }
            vals[i] = h + ':' + m;
            i++;
        });

        var monday = "2:" + vals[1] + ":" + vals[2];
        var tuesday = "3:" + vals[3] + ":" + vals[4];
        var wednesday = "4:" + vals[5] + ":" + vals[6];
        var thursday = "5:" + vals[7] + ":" + vals[8];
        var friday = "6:" + vals[9] + ":" + vals[10];
        var saturday = "7:" + vals[11] + ":" + vals[12];
        var sunday = "1:" + vals[13] + ":" + vals[14];


        $(".result").val(monday + "," + tuesday + "," + wednesday + "," + thursday + "," + friday + "," + saturday + "," + sunday);

        $(".result").select();

    }
</script>

{% endblock %}

templates/dars.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
<div class="table">
                    <table>
                        <tr class="bosh">
                            <th style="width: 5%;">№</th>
                            <th>Familyasi, ismi, otasining ism</th>
                            <th>casc sx c</th>
                            <th>c zzx s</th>
                        </tr>
                        {% for n in results %}
                        <tr>
                            <td>1</td>
                            <td>{{ n.0 }}</td>
                            <td>dcsa</td>
                        </tr>
                         {% endfor %}
                    </table>
                </div>





{% endblock %}

templates/ting.html
{% extends 'index.html' %}
{% load static %}
{% block content %}


<div class="mainbox">
    <div class="container">
        <div class="sectionHeader">
            <div class="textbox">
                <div class="tbox">
                    <h1>Tinglovchilarni ro‘yhatga olish</h1>
                    <h2>Shaxsiy ma'lumotlar va kontaktlar</h2>
                </div>
            </div>
        </div>
        <a href="{% url 'base_app:export_users_xlsx' %}"><input type="button" class="btn btn-succes">Kunlik hisobotni
            olish</a>
        <a href="{% url 'base_app:yakun' %}">Yakuniy hisobot</a>

        <form method="POST" action="{% url 'base_app:tinglovchi' %}">{% csrf_token %}
            <div class="row">
                <div class="name">
                    <div class="name_box">

                        <div class="col_box">
                            <p class="ism">FISH</p>
                            {{ form.FISH }}
                        </div>

                        <div class="col_box">
                            <p class="ism">MO yili</p>
                            {{ form.yil }}
                        </div>

                        <div class="col_box">
                            <p class="ism">MO oyi</p>
                            {{ form.oy }}
                        </div>
                        <div class="col_box">
                            <p class="ism">MO shakli</p>
                            {{ form.shakl }}
                        </div>

                        <input id="csrf_token" value="{{csrf_token}}" disabled hidden>
                        <div class="col_box">
                            <p class="ism">Hudud (Viloyat)</p>
                            {{ form.viloyat }}
                        </div>

                        <div class="col_box">
                            <p class="ism">Tuman</p>
                            {{ form.tuman }}
                        </div>

                        <div class="col_box">
                            <p class="ism">Ta’lim muassasasi nomi
                                (ish joyi)</p>
                            {{ form.joy }}
                        </div>


                    </div>

                    <div class="name_box">
                        <div class="col_box">
                            <p class="ism">Telefon</p>
                            {{form.tell}}
                        </div>

                        <div class="col_box">
                            <p class="ism">E-mail pochta</p>
                            {{ form.email }}
                        </div>

                        <div class="col_box">
                            <p class="ism">Malaka oshirish toifa</p>
                            {{ form.toifa }}
                        </div>

                        <div class="col_box">
                            <p class="ism">Guruh raqami</p>
                            {{ form.guruh }}
                        </div>
                        <div class="col_box">
                            <p class="ism">Ilmiy daraja</p>
                            {{ form.daraja }}
                        </div>

                        <div class="col_box">
                            <p class="ism">Himoya qilgan yil</p>
                            {{ form.himoya_yil }}
                        </div>
                        <div class="button">
                            <button class="btn1" id="save_btn" onclick="alert('Tinglovchi ro\'yxatga olindi')">Saqlash
                            </button>
                        </div>
                    </div>

                </div>

            </div>
        </form>
        {{ form.errors }}
    </div>
</div>
</section>
<script>

















$(document).ready(function (e) {
    document.getElementById('id_viloyat').addEventListener('change', e => {
        var a = document.getElementById("id_viloyat")
        var vil = a.value;
        var csrfToken = $('[name="csrfmiddlewaretoken"]').val();
        var data = {'csrfmiddlewaretoken': csrfToken};
        $.ajax({
            url: '/base_app/viloyat/',
            type: 'post',
            data: {
                'vil':vil,
                csrfmiddlewaretoken: $('#csrf_token').val()
                },
            'Content-type': 'application/json',
            success: function (res) {
                $('#id_tuman').empty()
                $.each(res['t'], function (i, v) {
                  
                    $('#id_tuman').append('<option value="' + v['id'] + '">' + v["name"] + '</option>')


                })
            },
            error: function (err) {
                console.log(err);
            }

        })
    });

    $('select[name="guruh"]').attr('disabled', true);
    document.getElementById("id_toifa").addEventListener("change", e=>{
        var a = document.getElementById("id_toifa")
        var toifa = a.value;
        if(toifa==1){
            $('select[name="guruh"]').removeAttr('disabled');
        console.log(toifa);
        var csrfToken = $('[name="csrfmiddlewaretoken"]').val();
        var data = {'csrfmiddlewaretoken': csrfToken};
        $.ajax({
            url: '/base_app/toifa/',
            type: 'post',
            data: {
                'toifa':toifa,
                csrfmiddlewaretoken: $('#csrf_token').val()
                },
            'Content-type': 'application/json',
            success: function (res) {
                $('#id_guruh').empty()
                $.each(res['guruh'], function (i, v) {
                  
                    $('#id_guruh').append('<option value="' + v['id'] + '">' + v["guruh"] + '</option>')


                })
            },
            error: function (err) {
                console.log(err);
            }
        })
    }else{
        $('select[name="guruh"]').attr('disabled', true);
    }




    })
        



    // document.getElementById("id_zaxira").addEventListener('change', e=>{
    //     toifa.attr("disabled", true);
    // });
    





})


</script>


{% endblock %}